In [ ]:
import pandas as pd
import numpy as np
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

In [ ]:
bm = pd.read_csv('/content/sample_data/bank_marketing_cleaned (2).csv')

In [ ]:
bm

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,pdays,previous,poutcome,emp_var_rate,cons_price_idx,cons_conf_idx,euribor3m,nr_employed,y,previously_contacted
0,44,blue-collar,married,basic.4y,unknown,yes,no,cellular,aug,thu,...,999,0,nonexistent,1.4,93.444,-36.1,4.963,5228.1,0,No
1,53,technician,married,unknown,no,no,no,cellular,nov,fri,...,999,0,nonexistent,-0.1,93.200,-42.0,4.021,5195.8,0,No
2,28,management,single,university.degree,no,yes,no,cellular,jun,thu,...,6,2,success,-1.7,94.055,-39.8,0.729,4991.6,1,Yes
3,39,services,married,high.school,no,no,no,cellular,apr,fri,...,999,0,nonexistent,-1.8,93.075,-47.1,1.405,5099.1,0,No
4,55,retired,married,basic.4y,no,yes,no,cellular,aug,fri,...,3,1,success,-2.9,92.201,-31.4,0.869,5076.2,1,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41183,59,retired,married,high.school,unknown,no,yes,telephone,jun,thu,...,999,0,nonexistent,1.4,94.465,-41.8,4.866,5228.1,0,No
41184,31,housemaid,married,basic.4y,unknown,no,no,telephone,may,thu,...,999,0,nonexistent,1.1,93.994,-36.4,4.860,5191.0,0,No
41185,42,admin.,single,university.degree,unknown,yes,yes,telephone,may,wed,...,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,0,No
41186,48,technician,married,professional.course,no,no,yes,telephone,oct,tue,...,999,0,nonexistent,-3.4,92.431,-26.9,0.742,5017.5,0,No
41187,25,student,single,high.school,no,no,no,telephone,may,fri,...,999,0,nonexistent,1.1,93.994,-36.4,4.859,5191.0,0,No

In [ ]:
bm.shape

(41188, 22)

In [ ]:
bm.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,pdays,previous,poutcome,emp_var_rate,cons_price_idx,cons_conf_idx,euribor3m,nr_employed,y,previously_contacted
0,44,blue-collar,married,basic.4y,unknown,yes,no,cellular,aug,thu,...,999,0,nonexistent,1.4,93.444,-36.1,4.963,5228.1,0,No
1,53,technician,married,unknown,no,no,no,cellular,nov,fri,...,999,0,nonexistent,-0.1,93.200,-42.0,4.021,5195.8,0,No
2,28,management,single,university.degree,no,yes,no,cellular,jun,thu,...,6,2,success,-1.7,94.055,-39.8,0.729,4991.6,1,Yes
3,39,services,married,high.school,no,no,no,cellular,apr,fri,...,999,0,nonexistent,-1.8,93.075,-47.1,1.405,5099.1,0,No
4,55,retired,married,basic.4y,no,yes,no,cellular,aug,fri,...,3,1,success,-2.9,92.201,-31.4,0.869,5076.2,1,Yes

In [ ]:
bm['y'].value_counts()

y
0    36548
1     4640
Name: count, dtype: int64

In [ ]:
bm['y'].value_counts()

Series([], Name: count, dtype: int64)

In [ ]:
bm.isnull().sum()

age                         0
job                         0
marital                     0
education                   0
default                     0
housing                     0
loan                        0
contact                     0
month                       0
day_of_week                 0
duration                    0
campaign                    0
pdays                       0
previous                    0
poutcome                    0
emp_var_rate                0
cons_price_idx              0
cons_conf_idx               0
euribor3m                   0
nr_employed                 0
y                       41188
previously_contacted        0
dtype: int64

In [ ]:
bm.isnull().sum().sum()

np.int64(41188)

In [ ]:
bm['previously_contacted'] = np.where(
    bm['pdays']==999,
    'no','yes'
)

In [ ]:
bm['previously_contacted'].value_counts()

previously_contacted
no     39673
yes     1515
Name: count, dtype: int64

In [ ]:
bm['pdays'] = bm['pdays'].replace(999,np.nan)

In [ ]:
bm['age_group'] = pd.cut(
    bm['age'],
    bins=[18,25,35,45,55,65,100],
    labels=['18-25','26-35','36-45','46-55','56-65','65+']
)

In [ ]:
bm['age_group'].value_counts().sort_index()

age_group
18-25     1633
26-35    14847
36-45    12844
46-55     8249
56-65     2963
65+        619
Name: count, dtype: int64

In [ ]:
bm['contact']=pd.cut(
    bm['campaign'],bins=[0,1,3,5,np.inf],
    labels=['low','Moderate','High','Very High']
)

In [ ]:
bm['contact'].value_counts()

contact
low          17642
Moderate     15911
High          4250
Very High     3385
Name: count, dtype: int64

In [ ]:
bm['previously_contacted']=np.where(
    bm['previous']>0,'yes','no'
)

In [ ]:
bm['previously_contacted'].value_counts()

previously_contacted
no     35563
yes     5625
Name: count, dtype: int64

In [ ]:
bm.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,previous,poutcome,emp_var_rate,cons_price_idx,cons_conf_idx,euribor3m,nr_employed,y,previously_contacted,age_group
0,44,blue-collar,married,basic.4y,unknown,yes,no,low,aug,thu,...,0,nonexistent,1.4,93.444,-36.1,4.963,5228.1,NaN,no,36-45
1,53,technician,married,unknown,no,no,no,low,nov,fri,...,0,nonexistent,-0.1,93.200,-42.0,4.021,5195.8,NaN,no,46-55
2,28,management,single,university.degree,no,yes,no,Moderate,jun,thu,...,2,success,-1.7,94.055,-39.8,0.729,4991.6,NaN,yes,26-35
3,39,services,married,high.school,no,no,no,Moderate,apr,fri,...,0,nonexistent,-1.8,93.075,-47.1,1.405,5099.1,NaN,no,36-45
4,55,retired,married,basic.4y,no,yes,no,low,aug,fri,...,1,success,-2.9,92.201,-31.4,0.869,5076.2,NaN,yes,46-55

In [ ]:
X= bm.drop('y',axis=1)
y= bm['y']

In [ ]:
print('X shape:',X.shape)
print('y shape:',y.shape)

X shape: (41188, 22)
y shape: (41188,)

In [ ]:
numeric_features = [
    'age',
    'campaign',
    'pdays',
    'previous',
    'emp_var_rate',
    'cons_price_idx',
    'cons_conf_idx',
    'euribor3m',
    'nr_employed'
]

In [ ]:
categorical_features = [
    'job',
    'marital',
    'education',
    'default',
    'housing',
    'loan',
    'contact',
    'month',
    'day_of_week',
    'poutcome',
    'previously_contacted',
    'age_group',
    'contact_intensity',
    'previous_campaign_contact'
]

In [ ]:
print("Numerical:", len(numeric_features))
print("Categorical:", len(categorical_features))

Numerical: 9
Categorical: 14

In [ ]:
numeric_transformer = Pipeline(
    steps=[
        ('imputer', SimpleImputer(strategy='median')),
        ('scaler', StandardScaler())
    ]
)

In [ ]:
categorical_transformer= Pipeline(
    steps=[
        ('imputer ', SimpleImputer (strategy='most_frequent')),
        ('onehot',OneHotEncoder(handle_unknown='ignore',sparse_output=False))
    ]
)

In [ ]:
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ]
)

In [ ]:
class_distribution = y.value_counts()

In [ ]:
print(
    y.value_counts(normalize=True)*100
)

Series([], Name: proportion, dtype: float64)

In [52]:
import os

output_dir = 'data'
os.makedirs(output_dir, exist_ok=True)

bm.to_csv(
    os.path.join(output_dir, 'bank_marketing_feature_engineered.csv'),
    index=False
)